### ISSUE TITLE
Setup Frontend architecture

### ISSUE THREAD

**Issue by christoph-codes** [Noceipt/noceipt-app#2]

**Comment by cmolisee** [comment]
@aaronschoi 
dev packages for testing
`npm install jest jest-environment-jsdom @testing-library/react @testing-library/user-event @testing-library/jest-dom @types/jest --save-dev`

**Comment by cmolisee** [comment]
@aaronschoi 
chalkra shit
`npm i @chakra-ui/react @emotion/react@^11 @emotion/styled@^11 framer-motion@^6`
